title: "Ajay Patel"
author: ""
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.md", title: "Blog"}
  - {file: "projects.md", title: "Projects"}
  - {url: "https://github.com/ajaypatel-8/ajaypatel-8.github.io/blob/master/ajay_patel-resume.pdf", title: "Resume"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ajpat8703@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ajaypatel-8"}
  - {title: Twitter, icon: twitter, url: "https://x.com/ajaypatel8_"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/ajay-patel-a88273216/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
